language: r
sudo: required
dist: trusty
cache:
  - packages
  - ccache

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - libnetcdf-dev
      - netcdf-bin

r_github_packages:
  - r-spatial/sf
  - r-spatial/stars
